[graphviz]
rankdir = "TD"

[doc]
columns = ["status"]

[doc.emoji.status]
"not-started" = "▯▯▯▯▯"
"exploration" = "▮▯▯▯▯"
"design" = "▮▮▯▯▯"
"implementation" = "▮▮▮▯▯"
"stabilization" = "▮▮▮▮▯"
"done" = "▮▮▮▮▮"

[doc.defaults]
status = "not-started"

[[group]]
name = "fundamentals"
label = "Rust fundamenta, stals"
description = [
  "Easy to contribute to the compiler",
  "Language semantics well understood",
  "Extending language possible by mere humans"
]
items = [
  { label = "Compiler libraries for MIR, types, traits", status = "implementation" },
  { label = "Core Rust semantics documented", status = "exploration" },
  { label = "Proof of soundness", status = "exploration" },
  { label = "Unsafe code guidelines", status = "design" },
]

[[group]]
name = "core-lang"
label = "Core language improvements"
description = [
  "Easy to contribute to the compiler",
]
requires = [
  "fundamentals",
]
items = [
  { label = "Dynamic dispatch (dyn trait) more powerful, easier to use", status = "design" },
  { label = "Specialization", status = "design" },
  { label = "Implied bounds", status = "design" },
  { label = "Generic associated types (GATs)", status = "implementation" },
  { label = "Impl trait", status = "stabilization" },
  { label = "Threaded contexts, capabilities", status = "design" },
]

[[group]]
name = "async-lang"
label = "Async I/O Fundamentals"
description = [
  "Using Async I/O comparable in complexity to Sync I/O",
  "Can author and use async libraries without thinking about runtimes",
  "Access to a wide variety of useful libraries on crates.io",
  "Easy to create and experiment with a specialized runtime",
]
requires = [
  "core-lang"
]
items = [
  { label = "Can use async fn everywhere", status = "implementation" },
  { label = "Async resource cleanup works well (async drop)", status = "design" },
  { label = "Easy interoperability between runtimes", status = "exploration" },
]

[[group]]
name = "async-stack"
label = "Async stack"
description = [
  "Can quickly stand up an async application",
  "Devs able to focus on 'business logic'",
]
requires = [
  "async-lang"
]
items = [
  { label = "High-performance runtime(s)", status = "implementation" },
  { label = "Logging", status = "implementation" },
  { label = "Testing", status = "exploration" },
  { label = "Persistence / database", status = "design" },
  { label = "Middleware", status = "design" },
  { label = "I/O uring support in tokio, other runtimes", status = "implementation" },
]

[[group]]
name = "onboarding-time"
label = "Smooth onboarding of Rust engineers"
requires = [
  "dev-tooling",
  "async-stack",
]
description = [
  "Time to be highly productive is measured in months",
  "Clear transition paths from other major languages",
]
items = [
  { label = "Rust beginner learning materials", status = "done" },
  { label = "Rust intermediate learning materials", status = "implementation" },
  { label = "Java transition path", status = "not-started" },
  { label = "C++ transition path", status = "design" },
  { label = "Dynamic language transition path", status = "design" },
]

[[group]]
name = "dev-tooling"
label = "Developer tooling"
requires = [
  "fundamentals"
]
description = [
  "Able to understand programs in terms of async behavior",
  "Able to fix correctness problems in development environment",
  "Able to fix performance problems in development environment",
]
items = [
  { label = "Quality Rust debugger", status = "design" },
  { label = "Rust well integrated into common IDEs", status = "stabilization" },
  { label = "Async runtime observability (e.g., tokio console)", status = "implementation" },
  { label = "Profilers for CPU and memory usage", status = "design" },
]

[[group]]
name = "prod-tooling"
label = "Production tooling"
requires = [
  "dev-tooling",
]
description = [
  "Able to troubleshoot correctness problems that arise in production",
  "Able to troubleshoot performance problems that arise in production",
]
items = [
  { label = "" },
]

[[group]]
name = "high-assurance"
label = "High assurance Rust"
requires = [
  "fundamentals",
]
description = [
  "Developers extending Rust with unsafe Rust can prove these extensions correct",
  "Developers can prove their Rust code meets functional specifications",
  "Developers can prove their Rust code meets specification",
]
items = [
  { label = "Sanitizer / dynamic checker for unsafe code", status = "exploration" },
  { label = "Model checker for Rust code", status = "exploration" },
  { label = "Packages on crates.io checked", status = "exploration" }
]

[[group]]
name = "well-integrated-into-internet-services"
label = "Rust is well integrated into internet services"
requires = [
  "onboarding-time",
]
description = [
  "SDKs for interacting with web services are readily available and complete",
  "FaaS platforms have first-class, convenient support for Rust",
]
items = [
  { label = "First-class support in AWS", status = "design" },
  { label = "First-class support in Azure", status = "?" },
  { label = "First-class support in GCP", status = "?" },
]

[[group]]
name = "goal-internet-services"
label = "🎯 Rust a common choice for internet services"
requires = [
  "onboarding-time",
  "well-integrated-into-internet-services",
  "prod-tooling",
  "high-assurance",
]
description = [
  "Operating costs and carbon impact are reduced",
  "Rate of vulnerabilities and high priority errors is reduced"
]
items = [
  { label = "Rust a common choice for building internet services", status = "design" },
  { label = "Rust a common choice for code that runs on internet services", status = "not-started" },
]

[[group]]
name = "goal-embedded"
label = "🎯 Rust a common choice for embedded applications"
requires = [
  "onboarding-time",
  "high-assurance",
]
description = [
  "?",
]
items = [
]
