[graphviz]
rankdir = "TD"

[doc]
include = [
  "include/prod-tooling.toml",
  "include/onboarding.toml",
]

[[group]]
name = "goal-internet-services"
label = "🎯 Rust a common choice for building internet services"
requires = [
  "onboarding-time",
  "prod-tooling",
  "dev-tooling",
]
description = [
  "Faster response times",
  "Ratio of P99.99 to P50 latencies is lower",
  "Data centers require fewer resources to sustain same level of traffic",
  "Common classes of security vulnerabilities are eliminated or significantly reduced",
  "Improved ability to recruit",
]
items = []