[graphviz]
rankdir = "TD"

[doc]
include = [
  "include/prod-tooling.toml",
  "include/onboarding.toml",
]

[[group]]
name = "goal-internet-services"
label = "🎯 Rust a common choice for programs running on internet services"
requires = [
  "onboarding-time",
  "prod-tooling",
]
description = [
  "Faster response times",
  "Ratio of P99.99 to P50 latencies is lower",
  "Data centers require fewer resources to sustain same level of traffic",
  "Rate of security vulnerabilities and serious bugs is dramatically reduced",
  "Improved employee retention and ability to recruit",
]
items = []