[graphviz]
rankdir = "TD"

[doc]
include = [
  "include/onboarding.toml",
  "include/debugging.toml",
  "include/development.toml",
]

[[group]]
name = "goal-internet-services"
label = "🎯 Rust a common choice for programs running on internet services"
requires = [
  "development",
  "onboarding",
  "debugging",
]
items = []