[doc]
include = [
  "expressive-lang.toml",
]

[[group]]
name = "async-lang"
label = "Rust supports Async I/O smoothly"
description = [
  "Using Async I/O comparable in complexity to Sync I/O",
  "Access to a wide variety of useful libraries on crates.io",
  "Easy access to high performance networking",
]
requires = [
  "expressive-lang"
]
items = [
  { label = "Can use async fn everywhere", status = "implementation" },
  { label = "Async resource cleanup works well (async drop)", status = "design" },
  { label = "Easy interoperability between runtimes", status = "exploration" },
  { label = "Async generators", status = "exploration" },
]

[[group]]
name = "async-stack"
label = "Rust offers a full-featured async stack"
description = [
  "Can quickly stand up an async application",
  "Devs able to focus on 'business logic'",
]
requires = [
  "async-lang",
]
items = [
  { label = "High-performance runtime(s)", status = "implementation" },
  { label = "Logging", status = "implementation" },
  { label = "Testing", status = "exploration" },
  { label = "Persistence / database", status = "design" },
  { label = "Middleware", status = "design" },
  { label = "I/O uring support in tokio, other runtimes", status = "implementation" },
]