[doc]
include = [
  "meta.toml",
]

[[group]]
name = "fundamentals"
label = "Compiler architecture is flexible and maintainable"
description = [
  "Easy to contribute to the compiler",
  "Language semantics well understood",
  "Extending language possible by mere humans"
]
items = [
  { label = "Rearchitect traits/borrow-checking as logical predicates", status = "implementation" },
  { label = "Core Rust semantics documented", status = "exploration" },
  { label = "Known soundness bugs closed", status = "design" },
]

[[group]]
name = "semi-stable-apis"
label = "Compiler offers semi-stable APIs that others can use"
requires = [
  "fundamentals",
]
items = [
  { label = "Shared crate for representing Rust types" },
  { label = "Access to Rust type information and type check results" },
  { label = "Ability to ask 'hypotheticals'" },
  { label = "Access to the MIR for a given function" },
]
