[doc]
include = [
  "compiler.toml",
]

[[group]]
name = "debugging"
label = "Able to fix (logic) bugs that are found during development"
requires = [
  "semi-stable-apis",
]
items = [
  { label = "Quality Rust debugger", status = "design" },
  { label = "Async runtime observability (e.g., tokio console)", status = "implementation" },
  { label = "Profilers for CPU and memory usage", status = "design" },
]