[doc]
include = [
  "compiler.toml",
  "ide.toml",
  "debugging.toml",
]

[[group]]
name = "development"
label = "Able to develop code and implement new features"
requires = [
    "onboarding",
    "debugging",
    "ide",
]
items = [
]