[doc]
include = [
  "compiler.toml",
]

[[group]]
name = "extensible"
label = "Extensible Rust"
description = [
  "Rust libraries can take control of the developer experience",
]
requires = [
  "semi-stable-apis",
]
items = [
  { label = "Macro hygiene", status = "design" },
  { label = "Libraries supply custom lints, errors", status = "not-started" },
  { label = "Libraries offering custom IDE integration (refactorings)", status = "exploration" },
  { label = "Macros, lints have access to type information", status = "exploration" },
]