[doc]
include = [
  "async.toml",
  "extensible.toml",
  "easy-lang.toml",
]

[[group]]
name = "onboarding"
label = "Able to onboard engineers quickly"
requires = [
  "async-stack",
  "extensible",
  "easy-lang",
]
items = [
  { label = "Rust beginner learning materials", status = "done" },
  { label = "Rust intermediate learning materials", status = "implementation" },
  { label = "Java transition path", status = "not-started" },
  { label = "C++ transition path", status = "design" },
  { label = "Dynamic language transition path", status = "design" },
]

