[doc]
debugging = [
  "debug.toml",
]

[[group]]
name = "production"
label = "Able to obtain metrics and logs and inspect state of services in production"
requires = [
  "debugging",
]
items = [
  { label = "Async runtime observability", status = "?" },
  { label = "Readable stacktraces, esp. in async", status = "design" },
  { label = "Live, low-overhead profilers for CPU and memory usage", status = "not-started" },
]
